class Constants:
    FONT_TYPEFACE = 'Ubuntu'
    FONT_SIZE_REGULAR = 14
    FONT_SIZE_DESCRIPTION = 12

    COLOUR_BACKGROUND = '#2A2A2E'
    COLOUR_TEXT = '#FAFAFA'
    COLOUR_LISTBOX_SELECTION_BACKGROUND = '#800080'
    COLOUR_LISTBOX_BACKGROUND = '#2A2A2E'
    COLOUR_LISTBOX_TEXT = '#ffffff'
    COLOUR_BUTTON_BACKGROUND = '#f1f1f1'

    # -----------------------
    ACTIVE_CURSOR = 'hand2'
    BUTTON_BORDER_SIZE = 0

    LISTBOX_WIDTH = 18
    LISTBOX_BORDER_SIZE = 0
    LISTBOX_HIGHLIGHT_THICKNESS = 0

    ENTRY_FONT_SIZE = 10
    ENTRY_BORDER_SIZE = 0
    ENTRY_WIDTH = 10
    ENTRY_NR_OF_CHARACTERS = 8
